[package]
name = "dot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
pest = "2.7.7"
pest_derive = "2.7.7"
[dev-dependencies]
rstest = "0.19"