[application]

# App (Project) Name
name = "dot-rs-testing-app"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dot-rs-testing-app"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundler]
# Bundle identifier
identifier = "io.github.dot_rs"

# Bundle publisher
publisher = "dot_rs"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["assets/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "dot_rs testing application"

# Bundle long description
long_description = """
An application used to help develop dot_rs: a dot library written in rust.
"""
