name: Enforce Clippy Lints including warnings, and Tests
on: push

# Fail CI on all warnings, including Clippy lints.
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets
      - run: cargo test --all-targets
